export const workflow=[
 {title:"Report",copy:"Capture what was lost, where it happened and when. A photo and a clear description make the first connection easier.",screen:"Let's find it.",status:"Open request",action:"Report created",note:"Reports stay within the selected campus in the mobile app."},
 {title:"Discover",copy:"Search organised requests by category, location, date and status. Give a potential finder enough context to recognise the item.",screen:"A familiar find.",status:"Potential match",action:"I found this item",note:"Sensitive numbers are removed from alert previews."},
 {title:"Match",copy:"The finder responds privately. The owner reviews the details and accepts or rejects the proposed match.",screen:"Could this be yours?",status:"Claim pending",action:"This is mine",note:"Only the owner and responding finder can view match details."},
 {title:"Verify",copy:"Confirm identifying details before arranging a handover. Phone contact unlocks only after the owner accepts a match.",screen:"The right connection.",status:"Match accepted",action:"Arrange handover",note:"Contact sharing follows the owner's selected preference."},
 {title:"Return",copy:"Meet directly or collect from the designated admin desk. The owner confirms the return, completing the journey.",screen:"Back where it belongs.",status:"Returned",action:"Return confirmed",note:"Only the owner can confirm that the item has been returned."}
];
export const solutions=[
 {slug:"cinemas",name:"Cinemas",headline:"Every seat. Every show. Every lost item.",copy:"Between the opening scene and the credits, things get lost. Give guests a calmer way to get them back.",image:"cinema",location:"Screen 03 · Row F",fields:["Screen","Row / seating area","Show time"],needs:["Capture the screen, row and show time in a report.","Coordinate the guest, floor team and collection desk.","Confirm the return before closing the request."]},
 {slug:"malls",name:"Malls",headline:"Thousands of visitors. One organised journey.",copy:"From the food court to the car park, bring scattered reports into one considered Lost & Found workflow.",image:"hero",location:"Level 2 · Central atrium",fields:["Floor","Store / zone","Approximate time"],needs:["Record the floor, store or zone where an item was lost.","Make reception and security handovers easier to follow.","Give visitors one clear place to start."]},
 {slug:"hotels",name:"Hotels",headline:"From room to reception. A way back.",copy:"A memorable stay shouldn't end with a missing belonging. Keep the next step clear for guests and teams.",image:"hero",location:"Lobby · Reception",fields:["Area / room","Stay date","Approximate time"],needs:["Capture the stay date and relevant room or public area.","Coordinate guest enquiries and designated collection.","Track a handover through to owner confirmation."]},
 {slug:"universities",name:"Universities",headline:"An entire campus. A closer connection.",copy:"Connect students, finders and the campus admin desk through the workflow where LnF began.",image:"campus",location:"Library · Ground floor",fields:["Campus","Building / zone","Approximate time"],needs:["Keep requests scoped to the relevant campus.","Use verified institutional identity in the mobile app.","Offer direct and admin-desk handover options."]},
 {slug:"events",name:"Events & venues",headline:"People come together. Belongings find their way back.",copy:"Make the post-event search less stressful with a clear route from report to collection.",image:"cinema",location:"Main hall · Entrance B",fields:["Event","Area / gate","Approximate time"],needs:["Capture the event, gate or seating zone.","Help the collection team organise incoming enquiries.","Maintain a clear record of the final return."]},
 {slug:"corporate",name:"Corporate campuses",headline:"One campus. One connected return journey.",copy:"A considered Lost & Found experience for employees, facilities and security teams.",image:"campus",location:"Building A · Reception",fields:["Building","Floor / zone","Approximate time"],needs:["Capture building, floor and zone information.","Keep private match details between the right participants.","Coordinate direct or designated-desk collection."]}
];
export const plans=[
 {name:"Start",tag:"One location",desc:"A focused starting point for a single venue or campus.",features:["Lost-item reporting","Search & filters","Private matching","Owner-confirmed returns"],cta:"Explore a pilot"},
 {name:"Enterprise",tag:"Growing organisations",desc:"A commercial direction for teams managing a busier return journey.",features:["Staff workflow · planned","Multi-location · planned","Recovery analytics · planned","Branded interface · planned"],cta:"Discuss your requirements"}
];
