"use client";
import Link from "next/link";

import { useEffect, useRef, useState } from "react";
import { Check, Upload, LockKeyhole } from "lucide-react";
import { Checkbox } from "@/components/ui/checkbox";
import { Progress } from "@/components/ui/progress";
import { Pick } from "./product";
import { solutions } from "@/lib/content";
const venueTypes=["University","Cinema","Mall","Hotel","Event / venue","Corporate campus","Other"];
const categoryOptions=["Electronics","Wallets","Bags","Keys","ID / bank card","Clothing","Other"];
const venueMap:Record<string,string>={universities:"University",cinemas:"Cinema",malls:"Mall",hotels:"Hotel",events:"Event / venue",corporate:"Corporate campus"};
function Field({label,id,children,help}:{label:string;id:string;children:React.ReactNode;help?:string}){return <div><label className="field-label" htmlFor={id}>{label}</label>{children}{help&&<p className="field-help">{help}</p>}</div>}
function Failure({message,auth,path}:{message:string;auth:boolean;path:string}){return message?<div className="form-error" role="alert">{message}{auth&&<> <a href={`/signin-with-chatgpt?return_to=${encodeURIComponent(path)}`} target="_top">Sign in with ChatGPT</a></>}</div>:null}
export function ReportForm({venue=""}:{venue?:string}){
 const [step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(""),[auth,setAuth]=useState(false),[reference,setReference]=useState(""),[consent,setConsent]=useState(false),[photo,setPhoto]=useState<File|null>(null),[preview,setPreview]=useState("");
 const [data,setData]=useState({title:"",category:"Other",description:"",venueType:venueMap[venue]??"University",organisation:"",place:"",zone:"",extra:"",eventDate:"",eventTime:"",contactMode:"In-app",contactValue:""});
 const heading=useRef<HTMLHeadingElement>(null);const update=(key:keyof typeof data,value:string)=>setData(d=>({...d,[key]:value}));
 const solution=solutions.find(s=>venueMap[s.slug]===data.venueType);const fields=solution?.fields??["Location","Area / zone","Approximate time"];
 function selectPhoto(file:File|null){setPhoto(file);setPreview(file?URL.createObjectURL(file):"")}
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 function changeStep(n:number){setStep(n);setError("");setTimeout(()=>heading.current?.focus(),0)}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");setAuth(false);if(step<2){changeStep(step+1);return}if(!consent){setError("Please accept the reporting-pilot notice before saving.");return}setBusy(true);const form=new FormData();for(const [key,value]of Object.entries(data))form.set(key,value);form.set("location",[data.place,data.zone,data.extra].filter(Boolean).join(" · "));form.set("consent","true");if(photo)form.set("photo",photo);try{const response=await fetch("/api/reports",{method:"POST",body:form});const result=await response.json() as {error?:string;reference:string};if(!response.ok){setAuth(response.status===401);throw new Error(result.error??"The report could not be saved.")}setReference(result.reference)}catch(e){setError(e instanceof Error?e.message:"Please check your connection and try again.")}finally{setBusy(false)}}
 if(reference)return <div className="form-panel"><div className="success-panel"><div className="success-icon"><Check size={28}/></div><h2>Your report is saved.</h2><p>Your private pilot report is ready to review.</p><span className="reference">{reference}</span><p>This report has not been sent to a venue or the campus mobile app. For an active search, contact the venue&apos;s official desk.</p><div className="button-row"><Link href="/my-reports" className="button ink">View my report</Link><button className="text-link" style={{background:"none",borderTop:0,borderRight:0,borderLeft:0}} onClick={()=>{setReference("");setStep(0);setConsent(false);selectPhoto(null);setData({...data,title:"",description:""})}}>Report another item</button></div></div></div>;
 return <div className="form-panel"><p className="form-step-label">STEP {step+1} OF 3 · {step===0?"THE ITEM":step===1?"THE MOMENT":"REVIEW & SAVE"}</p><Progress value={(step+1)/3*100} aria-label="Report progress" style={{height:3,marginBottom:28}}/><h2 ref={heading} tabIndex={-1}>{["What did you lose?","Where did it happen?","A considered next step."][step]}</h2><form onSubmit={submit}><div className="form-fields">
 {step===0&&<><Field label="Item name *" id="item-title"><input className="field-input" id="item-title" required maxLength={120} placeholder="e.g. Black leather wallet" value={data.title} onChange={e=>update("title",e.target.value)}/></Field><Field label="Category *" id="item-category"><Pick id="item-category" label="Item category" value={data.category} onChange={v=>update("category",v)} options={categoryOptions}/></Field>{data.category==="ID / bank card"&&<div className="form-warning">Describe the card holder or general appearance. Do not upload a readable card photo or enter card numbers, an ID number, a PIN or a password.</div>}<Field label="Description *" id="item-description" help="Use colour, material and distinguishing features. Keep sensitive identifiers private."><textarea id="item-description" className="field-input" rows={4} required minLength={10} maxLength={2000} placeholder="What would help someone recognise it?" value={data.description} onChange={e=>update("description",e.target.value)}/></Field><Field label="Photo (optional)" id="item-photo" help="JPG, PNG or WebP · up to 5 MB. Avoid confidential documents."><div className="upload-area"><Upload/><input id="item-photo" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const p=e.target.files?.[0]??null;if(p&&p.size>5*1024*1024){setError("Choose a photo 5 MB or smaller.");e.target.value="";selectPhoto(null);return}setError("");selectPhoto(p)}}/></div>{preview&&<img className="photo-preview" src={preview} alt="Selected report photo"/>}</Field></>}
 {step===1&&<><Field label="Organisation type *" id="venue-type"><Pick id="venue-type" label="Organisation type" value={data.venueType} onChange={v=>{update("venueType",v);update("place","");update("zone","");update("extra","")}} options={venueTypes}/></Field><Field label="Organisation / venue name *" id="organisation"><input id="organisation" className="field-input" required maxLength={200} placeholder="Name of the campus or venue" value={data.organisation} onChange={e=>update("organisation",e.target.value)}/></Field><Field label={`${fields[0]} *`} id="place"><input id="place" className="field-input" required maxLength={120} placeholder={fields[0]} value={data.place} onChange={e=>update("place",e.target.value)}/></Field><Field label={`${fields[1]} *`} id="zone"><input id="zone" className="field-input" required maxLength={120} placeholder={fields[1]} value={data.zone} onChange={e=>update("zone",e.target.value)}/></Field><div className="field-row"><Field label="Date lost *" id="lost-date"><input id="lost-date" type="date" required className="field-input" value={data.eventDate} max={new Date().toISOString().slice(0,10)} onChange={e=>update("eventDate",e.target.value)}/></Field><Field label="Approximate time" id="lost-time"><input id="lost-time" type="time" className="field-input" value={data.eventTime} onChange={e=>update("eventTime",e.target.value)}/></Field></div>{data.venueType==="Cinema"&&<Field label="Show (optional)" id="show"><input id="show" className="field-input" maxLength={120} placeholder="Film title / show" value={data.extra} onChange={e=>update("extra",e.target.value)}/></Field>}</>}
 {step===2&&<><dl><div className="review-row"><dt>Item</dt><dd>{data.title} · {data.category}</dd></div><div className="review-row"><dt>Venue</dt><dd>{data.organisation}<br/>{data.place} · {data.zone}</dd></div><div className="review-row"><dt>When</dt><dd>{data.eventDate}{data.eventTime&&` · ${data.eventTime}`}</dd></div><div className="review-row"><dt>Description</dt><dd>{data.description}</dd></div>{photo&&<div className="review-row"><dt>Photo</dt><dd>{photo.name}</dd></div>}</dl><Field label="Preferred contact mode *" id="contact-mode" help="This preference is recorded for a future connected workflow. The website pilot does not send notifications."><Pick id="contact-mode" label="Contact preference" value={data.contactMode} onChange={v=>{update("contactMode",v);update("contactValue","")}} options={["In-app","Email","Phone"]}/></Field>{data.contactMode!=="In-app"&&<Field label={`${data.contactMode==="Email"?"Email address":"Phone number"} *`} id="contact-value"><input className="field-input" id="contact-value" type={data.contactMode==="Email"?"email":"tel"} required maxLength={150} value={data.contactValue} onChange={e=>update("contactValue",e.target.value)}/></Field>}<div className="form-warning"><strong>Reporting pilot</strong><br/>Your report is private to your signed-in account. Venue staff, finders and the existing mobile app are not connected to this website yet.</div><label className="consent"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)} aria-label="Accept the reporting-pilot and privacy notice"/><span>I understand the pilot limitations and agree to store these details under the <Link href="/privacy" target="_blank">privacy notice</Link>.</span></label></>}
 </div><Failure message={error} auth={auth} path="/report"/><div className="form-actions">{step>0&&<button className="form-back" type="button" onClick={()=>changeStep(step-1)} disabled={busy}>Back</button>}<button className="button ink" type="submit" disabled={busy}>{busy?"Saving your report…":step<2?"Continue":"Save my report"}</button></div><p className="field-help" style={{marginTop:20,display:"flex",gap:7}}><LockKeyhole size={14}/>Private to your account · 14-day open-report window</p></form></div>
}
export function DemoForm({plan=""}:{plan?:string}) {
 const [data,setData]=useState({name:"",email:"",organisation:""}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[auth,setAuth]=useState(false),[reference,setReference]=useState("");
 const update=(key:keyof typeof data,value:string)=>setData(d=>({...d,[key]:value}));
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setAuth(false);try{const r=await fetch("/api/demo-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,plan})});const d=await r.json() as {error?:string;reference:string};if(!r.ok){setAuth(r.status===401);throw new Error(d.error??"Your enquiry could not be saved.")}setReference(d.reference)}catch(e){setError(e instanceof Error?e.message:"Please check your connection and try again.")}finally{setBusy(false)}}
 if(reference)return <div className="form-panel success-panel"><div className="success-icon"><Check size={28}/></div><h2>Your enquiry is saved.</h2><span className="reference">{reference}</span><p>Review your enquiry in My reports.</p><p>Email delivery and calendar booking are not connected in this version. No confirmation email or meeting has been sent.</p><div className="button-row"><Link className="button ink" href="/my-reports">View my enquiry</Link></div></div>;
 return <div className="form-panel"><h2>Tell us about your space.</h2><form onSubmit={submit}><div className="form-fields"><div className="field-row"><Field label="Your name *" id="demo-name"><input id="demo-name" required className="field-input" autoComplete="name" maxLength={120} value={data.name} onChange={e=>update("name",e.target.value)}/></Field><Field label="Work email *" id="demo-email"><input id="demo-email" type="email" required className="field-input" autoComplete="email" maxLength={150} value={data.email} onChange={e=>update("email",e.target.value)}/></Field></div><Field label="Organisation *" id="demo-organisation"><input id="demo-organisation" required className="field-input" autoComplete="organization" maxLength={200} value={data.organisation} onChange={e=>update("organisation",e.target.value)}/></Field></div><Failure message={error} auth={auth} path="/request-demo"/><div className="form-actions"><button className="button ink" type="submit" disabled={busy}>{busy?"Saving your enquiry…":"Request a demo"}</button></div><p className="field-help" style={{marginTop:18}}>By requesting a demo, you agree to our <Link href="/privacy" target="_blank">privacy notice</Link>. Your enquiry will be saved; email and calendar booking are not connected yet.</p></form></div>
}
export function MyReports(){const [reports,setReports]=useState<Record<string,unknown>[]>([]),[enquiries,setEnquiries]=useState<Record<string,unknown>[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState("");function load(){return Promise.all([fetch("/api/reports"),fetch("/api/demo-requests")]).then(async responses=>{const data=await Promise.all(responses.map(async r=>await r.json() as {error?:string;reports?:Record<string,unknown>[];enquiries?:Record<string,unknown>[]}));if(responses.some(r=>!r.ok))throw new Error(data.find(d=>d.error)?.error??"Your submissions could not be loaded.");return {reports:data[0].reports??[],enquiries:data[1].enquiries??[]}}).then(data=>{setReports(data.reports);setEnquiries(data.enquiries)}).catch(e=>{setError(e instanceof Error?e.message:"Please try again.")}).finally(()=>setBusy(false))}useEffect(()=>{void load()},[]);return <>{busy?<div className="empty-panel" role="status">Loading your saved submissions…</div>:error?<div className="form-error" role="alert">{error}<button className="text-link" onClick={()=>{setBusy(true);setError("");void load()}} style={{marginLeft:20,background:"none",border:0}}>Try again</button></div>:<>{!reports.length?<div className="empty-panel"><h2>A clear place to start.</h2><p>You haven&apos;t saved a lost-item report yet.</p><div className="button-row" style={{justifyContent:"center"}}><Link className="button ink" href="/report">Report a lost item</Link></div></div>:<div className="saved-reports">{reports.map(r=><article className="saved-report" key={String(r.id)}><div style={{display:"flex",justifyContent:"space-between",gap:15}}><span className="field-help">{String(r.reference)}</span><span className="state-pill">{r.status==="EXPIRED"?"Expired":"Open pilot report"}</span></div><h3>{String(r.title)}</h3><div className="report-meta">{String(r.organisation)} · {String(r.venueType)}<br/>{String(r.location)}<br/>{String(r.eventDate)}{r.eventTime?` · ${r.eventTime}`:""}</div><p className="report-desc">{String(r.description)}</p>{Boolean(r.photoKey)&&<img src={`/api/photos/${r.id}`} alt={`Your photo of ${r.title}`}/>}<p className="field-help" style={{marginTop:20}}>Saved privately. Venue teams and the campus app have not been notified.</p></article>)}</div>}{enquiries.length>0&&<section className="demo-inbox"><h2>Your demo enquiries</h2>{enquiries.map(r=><div className="inquiry-row" key={String(r.reference)}><div><strong>{String(r.organisation)}</strong><p className="field-help">{String(r.email)}{r.plan?` · ${String(r.plan)} plan`:""}</p></div><span className="field-help">{String(r.reference)}<br/>Saved · no email sent</span></div>)}</section>}</>}</>}
