
import Link from "next/link";
import { notFound } from "next/navigation";
import { Eyebrow } from "@/components/site/home";
import { DemoCTA } from "@/components/site/shell";
const articles:Record<string,{title:string;intro:string;sections:[string,string][]}>={
 "reporting-guide":{title:"A useful report starts with the right details.",intro:"A clear description helps a potential finder recognise a belonging without exposing information that belongs in a private conversation.",sections:[["Describe what someone can recognise","Include the item type, colour, size, brand if known and visible distinguishing features. For a wallet, describe its material and design rather than the cards inside it."],["Add location and time","Record the building, screen, floor or zone and an approximate time. If you moved between places, say where you last remember having the item."],["Use a photo carefully","A previous photo of the item can help. Crop out sensitive documents, account details and people who did not agree to be shown."],["Keep proof of ownership private","A unique mark, hidden detail or other identifying information can support a private verification. Keep full ID numbers, card numbers and passwords out of public descriptions."],["Choose the right reporting route","An active venue report must reach the organisation's official desk or connected system. The website pilot stores a private example; it does not alert venue teams."]]},
 "handover-guide":{title:"Finding it is half the journey.",intro:"A useful Lost & Found process stays open until the rightful owner confirms the belonging is back.",sections:[["Start with a private match","A finder provides identifying details through the controlled match flow. The owner reviews the details and accepts or rejects the proposed match."],["Agree on the handover route","Use a direct return or the organisation's designated collection desk. Record which route was chosen so the next step is clear."],["Track desk collection","The campus product includes submitted and collected states for an admin handover. A drop-off and a collection are separate events."],["Let the owner close the loop","Staff handling or a finder response alone should not mark an item as returned. Owner confirmation provides the final outcome."],["Keep a clear record","Retain the minimum information needed to explain the request, match and outcome. Wider staff access and venue configuration belong in the proposed commercial rollout."]]},
 "recovery-metrics":{title:"Measure the return, not just the report.",intro:"Good recovery metrics need clear definitions. A match is a promising step; a confirmed return is the completed outcome.",sections:[["Recovery rate","Define recovery rate as owner-confirmed returned items divided by total reports in the same cohort, multiplied by 100. State the period and whether expired or cancelled reports are included."],["Pending matches","Count reports with a proposed match still awaiting review or handover. Avoid treating these as successful recoveries."],["Average return time","Measure the elapsed time from report creation to owner-confirmed return. Only include completed returns and show the number of records behind the average."],["Location and category patterns","Use consistent location and category labels. Compare report and return counts together so a busy location does not automatically appear to perform poorly."],["Separate examples from outcomes","The website dashboard uses illustrative records and calculates its preview totals from those records. It does not represent customer traction or measured production performance."]]}
};
export async function generateMetadata({params}:{params:Promise<{article:string}>}){const{article}=await params;return{title:articles[article]?.title??"Resource"}}
export default async function Resource({params}:{params:Promise<{article:string}>}){const{article}=await params;const a=articles[article];if(!a)notFound();return <main id="main"><section className="page-intro"><div className="wrap"><Eyebrow>Resources / Practical guide</Eyebrow><h1>{a.title}</h1><p>{a.intro}</p></div></section><section className="section" style={{paddingTop:0}}><div className="wrap article-layout">{a.sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}<Link className="text-link" href="/resources">All resources</Link></div></section><DemoCTA/></main>}
